# Ref for actions.yml
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
# Ref for conventional commit
# https://www.conventionalcommits.org/en/v1.0.0/

name: 'Semantic Issue Actions'
description: 'Check issues title with convensional commits format'
author: 'hwakabh'

inputs:
  token: # id of input
    description: 'GitHub Tokens for the actions'
    required: true
    default: ${{ github.token }}
  repo:
    description: 'Repository to enforce semantic issue'
    required: true
    default: 'hwakabh/semantic-issue-action'
  body:
    description: 'Message body to comment if title is not semantic'
    required: false
    default: 'The issue title is not aligned to conventional-commits specs, please consider to resolve.'
outputs:
  check-result: # id of output
    description: 'Results of checking following the specs or not'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'github'
  color: 'green'
